json_table_create = ("""
    CREATE TABLE IF NOT EXISTS json_table (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ingested_at timestamp DEFAULT CURRENT_TIMESTAMP,
        data jsonb NOT NULL
    );
""")

json_table_copy = ("""
    COPY json_table (data) FROM STDIN;
""")

table_queries = [json_table_create, json_table_copy]

print(table_queries[0])